CRITICAL - 2020-09-26 02:28:14 --> Table 'ci_app.users' doesn't exist
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Model.php(506): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Validation\UserAuth.php(11): CodeIgniter\Model->first()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(325): App\Validation\UserAuth->validateUser('sdfsdfsfd', 'email, password', Array, NULL)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('password', 'password', 'sdfsdfsfd', Array, Array)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array, Array)
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#12 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2020-09-26 02:57:51 --> default is not a valid database connection group.
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(263): CodeIgniter\Database\Config::connect('default', true)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(176): db_connect(NULL)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Config\Services.php(470): CodeIgniter\Database\MigrationRunner->__construct(NULL, NULL)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Config\BaseService.php(123): CodeIgniter\Config\Services::migrations(Object(Config\Migrations), NULL, false)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Config\Services.php(465): CodeIgniter\Config\BaseService::getSharedInstance('migrations', NULL, NULL)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(107): CodeIgniter\Config\Services::migrations()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\techorigin_works\codeigniter_app\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-09-26 03:02:49 --> default is not a valid database connection group.
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(263): CodeIgniter\Database\Config::connect('default', true)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(176): db_connect(NULL)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Config\Services.php(470): CodeIgniter\Database\MigrationRunner->__construct(NULL, NULL)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Config\BaseService.php(123): CodeIgniter\Config\Services::migrations(Object(Config\Migrations), NULL, false)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Config\Services.php(465): CodeIgniter\Config\BaseService::getSharedInstance('migrations', NULL, NULL)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(107): CodeIgniter\Config\Services::migrations()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\techorigin_works\codeigniter_app\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-09-26 03:05:08 --> default is not a valid database connection group.
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Model.php(352): CodeIgniter\Database\Config::connect('default')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(18): CodeIgniter\Model->__construct()
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Validation\UserAuth.php(8): App\Models\UserModel->__construct()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(325): App\Validation\UserAuth->validateUser('asdsadasdasdasd', 'email, password', Array, NULL)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asdsadasdasdasd', Array, Array)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array, Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-09-26 03:06:09 --> default is not a valid database connection group.
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(263): CodeIgniter\Database\Config::connect('default', true)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(176): db_connect(NULL)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Config\Services.php(470): CodeIgniter\Database\MigrationRunner->__construct(NULL, NULL)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Config\BaseService.php(123): CodeIgniter\Config\Services::migrations(Object(Config\Migrations), NULL, false)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Config\Services.php(465): CodeIgniter\Config\BaseService::getSharedInstance('migrations', NULL, NULL)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(107): CodeIgniter\Config\Services::migrations()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\techorigin_works\codeigniter_app\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-09-26 03:49:36 --> Call to a member function passwordHash() on null
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Validation\UserAuth.php(8): App\Models\UserModel->__construct()
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(325): App\Validation\UserAuth->validateUser('asdasdasd', 'email, password', Array, NULL)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asdasdasd', Array, Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array, Array)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 03:51:07 --> Call to a member function passwordHash() on null
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Validation\UserAuth.php(8): App\Models\UserModel->__construct()
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(325): App\Validation\UserAuth->validateUser('asdasdasd', 'email, password', Array, NULL)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asdasdasd', Array, Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array, Array)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 03:52:14 --> Call to a member function helper() on null
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Validation\UserAuth.php(8): App\Models\UserModel->__construct()
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(325): App\Validation\UserAuth->validateUser('asdasdasd', 'email, password', Array, NULL)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asdasdasd', Array, Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array, Array)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 03:53:36 --> Call to a member function passwordHash() on null
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Validation\UserAuth.php(8): App\Models\UserModel->__construct()
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(325): App\Validation\UserAuth->validateUser('asdasdasd', 'email, password', Array, NULL)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asdasdasd', Array, Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array, Array)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 03:53:37 --> Call to a member function passwordHash() on null
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Validation\UserAuth.php(8): App\Models\UserModel->__construct()
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(325): App\Validation\UserAuth->validateUser('asdasdasd', 'email, password', Array, NULL)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asdasdasd', Array, Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(26): CodeIgniter\Controller->validate(Array, Array)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 04:29:26 --> Invalid file: templates/include/header.php
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('templates/inclu...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/inclu...', Array, true)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(90): view('templates/inclu...', Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->register()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-09-26 04:29:47 --> include_once(../app/Views/templates/include/css.php): failed to open stream: No such file or directory
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\header.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include_once(.....', 'C:\\xampp\\htdocs...', 6, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\header.php(6): include_once()
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/heade...', Array, true)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(90): view('templates/heade...', Array)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->register()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 04:31:52 --> include_once(../app/Views/templates/include/scripts.php): failed to open stream: No such file or directory
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\footer.php(48): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include_once(.....', 'C:\\xampp\\htdocs...', 48, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\footer.php(48): include_once()
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/foote...', Array, true)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(92): view('templates/foote...')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->register()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 04:45:31 --> Undefined index: email
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Validation\UserAuth.php(10): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 10, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(325): App\Validation\UserAuth->validateUser('aaassdsds', 'email, password', Array, NULL)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('password', 'password', 'aaassdsds', Array, Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array, Array)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 05:00:32 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':username OR `email` = :email LIMIT 1' at line 2
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT * FROM `...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM `...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM `...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(25): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...', Array)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(28): App\Models\UserModel->authUserByUsernameOrEmain('SuperAdmin', 'ABCtest123!')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 05:01:17 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':username OR `email` = :email LIMIT 1' at line 2
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT * FROM `...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM `...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM `...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(25): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...', Array)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(28): App\Models\UserModel->authUserByUsernameOrEmain('SuperAdmin', 'ABCtest123!')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 05:01:54 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':username OR `email` = :email LIMIT 1' at line 2
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT * FROM `...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM `...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM `...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(25): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...', Array)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(28): App\Models\UserModel->authUserByUsernameOrEmain('SuperAdmin', 'ABCtest123!')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 05:02:18 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':username OR `email` = :email LIMIT 1' at line 2
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT * FROM `...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM `...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM `...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(25): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...', Array)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(28): App\Models\UserModel->authUserByUsernameOrEmain('SuperAdmin', 'ABCtest123!')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 05:04:20 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':username OR `email` = :email LIMIT 1' at line 2
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT * FROM `...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM `...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM `...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(25): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...', Array)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(28): App\Models\UserModel->authUserByUsernameOrEmain('SuperAdmin', 'ABCtest123!')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-09-26 05:16:27 --> Encrypter needs a starter key.
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Encryption\Encryption.php(155): CodeIgniter\Encryption\Exceptions\EncryptionException::forNeedsStarterKey()
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Config\Services.php(251): CodeIgniter\Encryption\Encryption->initialize(Object(Config\Encryption))
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(5): CodeIgniter\Config\Services::encrypter()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(365): require_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\User...')
#6 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\User...')
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Validation\UserAuth.php(8): spl_autoload_call('App\\Models\\User...')
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(325): App\Validation\UserAuth->validateUser('ABCtest123!', 'username, passw...', Array, NULL)
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('password', 'password', 'ABCtest123!', Array, Array)
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(24): CodeIgniter\Controller->validate(Array, Array)
#12 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#13 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#14 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#17 {main}
CRITICAL - 2020-09-26 05:17:16 --> Undefined variable: encrypter
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(43): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 43, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(31): App\Models\UserModel->setUserSession(Array)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2020-09-26 05:19:45 --> Undefined variable: encrypter
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(43): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 43, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(31): App\Models\UserModel->setUserSession(Array)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2020-09-26 06:45:11 --> Call to a member function library() on null
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(31): App\Models\UserModel->setUserSession(Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-09-26 06:59:20 --> print_r() expects at least 1 parameter, 0 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r() expec...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(26): print_r()
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(22): App\Models\UserModel->checkSignIn()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(11): App\Models\UserModel->__construct()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-09-26 07:11:47 --> Trying to get property 'role_id' of non-object
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(28): App\Models\UserModel->signInWithSession()
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(22): App\Models\UserModel->checkSignIn()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Users.php(11): App\Models\UserModel->__construct()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Users->index()
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-09-26 07:19:32 --> Undefined variable: data
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Protals.php(16): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 16, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Protals->index()
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Protals))
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-09-26 07:20:22 --> Undefined variable: data
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Portals.php(16): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 16, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Portals->index()
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Portals))
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-09-26 07:58:29 --> file_get_contents(../assets/data/personal.json): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 38, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav-bar.php(38): file_get_contents('../assets/data/...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav.php(23): include_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\header.php(30): include_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/heade...', Array, true)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Portals.php(18): view('templates/heade...', Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Portals->index()
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Portals))
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-09-26 07:58:44 --> file_get_contents(/assets/data/personal.json): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 38, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav-bar.php(38): file_get_contents('/assets/data/pe...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav.php(23): include_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\header.php(30): include_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/heade...', Array, true)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Portals.php(18): view('templates/heade...', Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Portals->index()
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Portals))
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-09-26 07:59:28 --> file_get_contents(../../assets/data/personal.json): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 38, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav-bar.php(38): file_get_contents('../../assets/da...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav.php(23): include_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\header.php(30): include_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/heade...', Array, true)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Portals.php(18): view('templates/heade...', Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Portals->index()
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Portals))
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-09-26 07:59:38 --> file_get_contents(../../../assets/data/personal.json): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 38, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav-bar.php(38): file_get_contents('../../../assets...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav.php(23): include_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\header.php(30): include_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/heade...', Array, true)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Portals.php(18): view('templates/heade...', Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Portals->index()
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Portals))
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-09-26 07:59:43 --> file_get_contents(../../../../assets/data/personal.json): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 38, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav-bar.php(38): file_get_contents('../../../../ass...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav.php(23): include_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\header.php(30): include_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/heade...', Array, true)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Portals.php(18): view('templates/heade...', Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Portals->index()
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Portals))
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-09-26 07:59:50 --> file_get_contents(/assets/data/chat.json): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 39, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav-bar.php(39): file_get_contents('/assets/data/ch...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav.php(23): include_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\header.php(30): include_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/heade...', Array, true)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Portals.php(18): view('templates/heade...', Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Portals->index()
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Portals))
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-09-26 07:59:57 --> file_get_contents(/assets/data/chat.json): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 39, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav-bar.php(39): file_get_contents('/assets/data/ch...')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav.php(23): include_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\header.php(30): include_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/heade...', Array, true)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Portals.php(18): view('templates/heade...', Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Portals->index()
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Portals))
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-09-26 08:09:39 --> userscheck filter must have a matching alias defined.
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Filters\Filters.php(150): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('userscheck')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('portals', 'before')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-09-26 08:09:52 --> userscheck filter must have a matching alias defined.
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Filters\Filters.php(150): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('userscheck')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('portals', 'before')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-09-26 08:09:53 --> userscheck filter must have a matching alias defined.
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Filters\Filters.php(150): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('userscheck')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('portals', 'before')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-09-26 08:09:55 --> userscheck filter must have a matching alias defined.
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Filters\Filters.php(150): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('userscheck')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('/', 'before')
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-09-26 08:13:14 --> Invalid file: pages/signin.php
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pages/signin.ph...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('pages/signin', Array, true)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Pages.php(42): view('pages/signin', Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Pages->signin()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-09-26 08:13:18 --> Invalid file: pages/signin.php
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pages/signin.ph...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('pages/signin', Array, true)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Pages.php(42): view('pages/signin', Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Pages->signin()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-09-26 08:14:20 --> Invalid file: pages/signin.php
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pages/signin.ph...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('pages/signin', Array, true)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Pages.php(42): view('pages/signin', Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Pages->signin()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-09-26 08:14:21 --> Invalid file: pages/signin.php
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pages/signin.ph...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('pages/signin', Array, true)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Pages.php(42): view('pages/signin', Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Pages->signin()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-09-26 08:14:43 --> Invalid file: pages/signin.php
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pages/signin.ph...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('pages/signin', Array, true)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Pages.php(42): view('pages/signin', Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Pages->signin()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-09-26 08:14:44 --> Invalid file: pages/signin.php
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pages/signin.ph...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('pages/signin', Array, true)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Pages.php(42): view('pages/signin', Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Pages->signin()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-09-26 08:14:45 --> Invalid file: pages/signin.php
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pages/signin.ph...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('pages/signin', Array, true)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Pages.php(42): view('pages/signin', Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Pages->signin()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-09-26 08:14:53 --> Invalid file: pages/signin.php
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pages/signin.ph...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('pages/signin', Array, true)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Pages.php(42): view('pages/signin', Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Pages->signin()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-09-26 08:14:53 --> Invalid file: pages/signin.php
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pages/signin.ph...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('pages/signin', Array, true)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Pages.php(42): view('pages/signin', Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Pages->signin()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-09-26 08:15:27 --> Invalid file: pages/signin.php
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pages/signin.ph...')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('pages/signin', Array, true)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Pages.php(43): view('pages/signin', Array)
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Pages->signin()
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-09-26 08:26:37 --> Class 'App\Filters\AuthUser' not found
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('portals', 'before')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2020-09-26 08:26:54 --> Class 'App\Filters\AuthUser' not found
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('portals', 'before')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2020-09-26 08:26:55 --> Class 'App\Filters\AuthUser' not found
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('portals', 'before')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2020-09-26 08:26:56 --> Class 'App\Filters\AuthUser' not found
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('portals', 'before')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2020-09-26 08:28:35 --> Class 'App\Filters\AuthUser' not found
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('portals', 'before')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2020-09-26 09:01:24 --> Trying to get property 'is_admin' of non-object
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Models\UserModel.php(118): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 118, Array)
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav-bar.php(218): App\Models\UserModel->isAdmin()
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\topnav.php(23): include_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Views\templates\header.php(30): include_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/heade...', Array, true)
#6 C:\xampp\htdocs\techorigin_works\codeigniter_app\app\Controllers\Portals.php(15): view('templates/heade...', Array)
#7 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Portals->index()
#8 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Portals))
#9 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2020-09-26 12:36:15 --> Class 'App\Filters\AdminUser' not found
#0 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('admins', 'before')
#1 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\techorigin_works\codeigniter_app\public\index.php(45): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\techorigin_works\codeigniter_app\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#4 {main}
